### ISSUE TITLE
Xfer OTT - download fail

### ISSUE THREAD

**Issue by KamikazeVildsvin** [mofeing/homebrew-audio-plugins#5]
Hi, i get an error when i try to download OTT.

```
==> Downloading https://xferrecords.com/product_downloads/24/freeware
curl: (22) The requested URL returned error: 403

Error: Download failed on Cask 'xfer-ott' with message: Download failed: https://xferrecords.com/product_downloads/24/freeware
```
Thanks

**Comment by mofeing** [comment]
@KamikazeVildsvin i haven't updated the links for a while. If you find the correct link, you can post it here or better do a pull request.

I would appreacite it.

**Comment by KamikazeVildsvin** [comment]
I think it has something to do with the version. This is the actual dmg:
Install_Xfer_OTT_135.dmg

**Comment by mofeing** [comment]
Strange because i just typed [https://xferrecords.com/product_downloads/24/freeware](https://xferrecords.com/product_downloads/24/freeware) in my browser and it downloaded the dmg.

Does it work for you?

**Comment by KamikazeVildsvin** [comment]
Yes, it works for me. So i'm not sure why the error appears in brew. I don't really know anything about how Ruby files work, but I can see that the name of the downloaded package is `Install_Xfer_OTT_135.dmg` and not `Install_Xfer_OTT.dmg` like in the .rb file.

Maybe this makes a difference?

**Comment by mofeing** [comment]
Well, the problem is on the download step, not on the versioning. I tried running it manually and looks like xferrecords.com is behind the Cloudflare proxy and it detects us (i.e. Homebrew) as a potential threat. As such, it makes us pass a CAPTCHA but `curl` cannot solve it so it fails and returns a 403 error.

It is not something tha I can solve. Sorry. If you find an alternative link, I will be open to modify it.
